class Template:
    name = "Marouane"
    profession = "Web Developer"
    email = "marouane@example.com"
    phone = "+1234567890"
    profile = "Experienced web developer with a passion for creating clean and efficient code."
    skill1 = "HTML"
    skill1_desc = "Proficient in creating semantic and accessible HTML markup."
    skill2 = "CSS"
    skill2_desc = "Skilled in styling websites using CSS, including frameworks like Bootstrap."
    skill3 = "JavaScript"
    skill3_desc = "Familiar with JavaScript and libraries like jQuery for interactive web development."
    tech1 = "XHTML"
    tech2 = "CSS"
    tech3 = "JavaScript"
    tech4 = "Python"
    tech5 = "PHP"
    tech6 = "MySQL"
    tech7 = "Git"
    tech8 = "Linux"
    tech9 = "Adobe Photoshop"
    exp1_company = "ABC Web Solutions"
    exp1_title = "Junior Web Developer"
    exp1_dates = "2018-2020"
    exp1_desc = "Developed and maintained websites for clients using HTML, CSS, and JavaScript."
    exp2_company = "XYZ Tech"
    exp2_title = "Frontend Developer"
    exp2_dates = "2020-2022"
    exp2_desc = "Worked on improving user interfaces and experiences for various web applications."
    exp3_company = "Tech Innovations"
    exp3_title = "Senior Web Developer"
    exp3_dates = "2022-present"
    exp3_desc = "Lead a team of developers in creating innovative web solutions for clients."
    exp4_company = "Previous Company"
    exp4_title = "Previous Role"
    exp4_dates = "Previous Dates"
    exp4_desc = "Previous Description"
    edu_institution = "University of Technology"
    edu_degree = "Bachelor of Science in Computer Science"
    edu_gpa = "3.8"


    def __init__(self) -> None:
        self.__dict__ = {k:v for k, v in vars(self.__class__).items() if not k.startswith("__")}